version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: factory_bot_rails
    versions:
    - "< 6, >= 5.a"
  - dependency-name: tinymce-rails
    versions:
    - ">= 5.a, < 6"
  - dependency-name: omniauth
    versions:
    - 2.0.3
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.3.1
    - 6.1.4
  - dependency-name: aws-sdk-s3
    versions:
    - 1.88.2
    - 1.90.0
